title: "Radix-Gamma Labs"
author: "Astrea Rojas"
description: "The Radix-Gamma Project."
theme: minima
baseurl: "/"
url: "https://the-red-crow.github.io"
header_pages:
  - about.md
  - Research:
    - msthesis.md
