title: "Radix-γ Labs"
author: "Astrea Rojas"
description: "The Radix-γ Project."
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
baseurl: "/"
url: "https://the-red-crow.github.io"
nav_pages:
  - about.md
  - Research:
    - research/msthesis.md
    - research/trinity.md
